<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Accommodation;

class AccommodationSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            ['judul' => "Cabin 1", 'jenis' => "Cabin", 'kasur' => "Queen Bed (140×200)", 'merokok' => true, 'fasilitas' => ["TV kabel","Meja","Lemari es","TV","Ruang tamu","Balkon","Dapur","Kipas angin"], 'makanan' => ["Fasilitas Membuat Kopi/Teh","Air Minum Gratis","Sarapan 6 pax"], 'max_orang' => 4, 'catatan' => ["Anak di bawah umur 5 tahun Free, maksimal 2 anak.","Tambahan anak di atas 5 tahun 75k/orang","Tambahan dewasa di atas 17 tahun 100k/orang"], 'slot' => 6, 'harga_weekday' => 1200000, 'harga_weekend' => 1400000, 'harga_highseason' => 1800000, 'gambar' => "images/akomodasi/cabin1/a.png"],
            ['judul' => "Rumah Industrial 1", 'jenis' => "Rumah Industrial", 'kasur' => "Queen Bed (140×200)", 'merokok' => true, 'fasilitas' => ["TV kabel","Meja","Lemari es","TV","Ruang tamu","Balkon","Dapur","Kipas angin"], 'makanan' => ["Fasilitas Membuat Kopi/Teh","Air Minum Gratis","Sarapan 6 pax"], 'max_orang' => 4, 'catatan' => ["Anak di bawah umur 5 tahun Free, maksimal 2 anak.","Tambahan anak di atas 5 tahun 75k/orang","Tambahan dewasa di atas 17 tahun 100k/orang"], 'slot' => 4, 'harga_weekday' => 921609, 'harga_weekend' => 1100000, 'harga_highseason' => 1400000, 'gambar' => "images/akomodasi/industrial1/a.png"],
            ['judul' => "Glamping VIP", 'jenis' => "Glamping", 'kasur' => "1 Tenda Arpenaz Quechua", 'merokok' => true, 'fasilitas' => ["Matras kasur tebal 15cm","1 lampu tenda","1 meja lesehan","VIP Eksklusif","Colokan listrik 3 cabang"], 'makanan' => ["Teh, gula, dan kopi","2 mineral botol 1.5 liter"], 'max_orang' => 4, 'catatan' => ["Anak di bawah umur 5 tahun Free, maksimal 2 anak.","Tambahan anak di atas 5 tahun 75k/orang"], 'slot' => 6, 'harga_weekday' => 921609, 'harga_weekend' => 1100000, 'harga_highseason' => 1400000, 'gambar' => "images/akomodasi/glamping_vip/a.png"],
            ['judul' => "Cabin 2", 'jenis' => "Cabin", 'kasur' => "Queen Bed (140×200)", 'merokok' => false, 'fasilitas' => ["TV kabel","Meja","Lemari es","Balkon","Dapur","AC"], 'makanan' => ["Fasilitas Membuat Kopi/Teh","Air Minum Gratis","Sarapan 4 pax"], 'max_orang' => 3, 'catatan' => ["Anak di bawah umur 5 tahun Free"], 'slot' => 3, 'harga_weekday' => 950000, 'harga_weekend' => 1150000, 'harga_highseason' => 1500000, 'gambar' => "images/akomodasi/cabin2/a.png"],
            ['judul' => "Cabin 3", 'jenis' => "Cabin", 'kasur' => "Twin Bed (2×100×200)", 'merokok' => true, 'fasilitas' => ["TV kabel","Meja","Lemari es","Balkon","Kipas angin"], 'makanan' => ["Fasilitas Membuat Kopi/Teh","Air Minum Gratis","Sarapan 4 pax"], 'max_orang' => 4, 'catatan' => ["Anak di bawah umur 5 tahun Free"], 'slot' => 5, 'harga_weekday' => 880000, 'harga_weekend' => 1050000, 'harga_highseason' => 1350000, 'gambar' => "images/akomodasi/cabin3/a.png"],
            ['judul' => "Cabin 4", 'jenis' => "Cabin", 'kasur' => "Queen Bed (140×200)", 'merokok' => false, 'fasilitas' => ["TV kabel","Meja","AC","Balkon","Dapur"], 'makanan' => ["Air Minum Gratis","Sarapan 4 pax"], 'max_orang' => 3, 'catatan' => ["Anak di bawah umur 5 tahun Free"], 'slot' => 4, 'harga_weekday' => 870000, 'harga_weekend' => 1020000, 'harga_highseason' => 1300000, 'gambar' => "images/akomodasi/cabin4/a.png"],
            ['judul' => "Cabin 5", 'jenis' => "Cabin", 'kasur' => "King Bed (180×200)", 'merokok' => true, 'fasilitas' => ["TV kabel","Meja","Lemari es","AC","Ruang tamu","Balkon","Dapur"], 'makanan' => ["Fasilitas Membuat Kopi/Teh","Air Minum Gratis","Sarapan 6 pax"], 'max_orang' => 5, 'catatan' => ["Anak di bawah umur 5 tahun Free"], 'slot' => 3, 'harga_weekday' => 1350000, 'harga_weekend' => 1550000, 'harga_highseason' => 1950000, 'gambar' => "images/akomodasi/cabin5/a.png"],
            ['judul' => "Cabin 6", 'jenis' => "Cabin", 'kasur' => "Queen Bed (140×200)", 'merokok' => false, 'fasilitas' => ["TV kabel","Meja","Kipas angin","Balkon"], 'makanan' => ["Air Minum Gratis","Sarapan 2 pax"], 'max_orang' => 2, 'catatan' => ["Anak di bawah umur 5 tahun Free"], 'slot' => 5, 'harga_weekday' => 750000, 'harga_weekend' => 900000, 'harga_highseason' => 1150000, 'gambar' => "images/akomodasi/cabin6/a.png"],
            ['judul' => "Cabin 7", 'jenis' => "Cabin", 'kasur' => "Twin Bed (2×100×200)", 'merokok' => true, 'fasilitas' => ["TV kabel","Meja","Lemari es","Dapur","Kipas angin"], 'makanan' => ["Fasilitas Membuat Kopi/Teh","Air Minum Gratis","Sarapan 4 pax"], 'max_orang' => 4, 'catatan' => ["Anak di bawah umur 5 tahun Free"], 'slot' => 4, 'harga_weekday' => 900000, 'harga_weekend' => 1080000, 'harga_highseason' => 1380000, 'gambar' => "images/akomodasi/cabin7/a.png"],
            ['judul' => "Cabin 8", 'jenis' => "Cabin", 'kasur' => "Queen Bed (140×200)", 'merokok' => false, 'fasilitas' => ["TV kabel","Meja","AC","Lemari es","Balkon","Dapur"], 'makanan' => ["Fasilitas Membuat Kopi/Teh","Air Minum Gratis","Sarapan 4 pax"], 'max_orang' => 3, 'catatan' => ["Anak di bawah umur 5 tahun Free"], 'slot' => 6, 'harga_weekday' => 980000, 'harga_weekend' => 1160000, 'harga_highseason' => 1480000, 'gambar' => "images/akomodasi/cabin8/a.png"],
            ['judul' => "Rumah Industrial 2", 'jenis' => "Rumah Industrial", 'kasur' => "Queen Bed (140×200)", 'merokok' => true, 'fasilitas' => ["TV kabel","Meja","Lemari es","Ruang tamu","Balkon","Dapur","Kipas angin"], 'makanan' => ["Fasilitas Membuat Kopi/Teh","Air Minum Gratis","Sarapan 6 pax"], 'max_orang' => 4, 'catatan' => ["Anak di bawah umur 5 tahun Free"], 'slot' => 3, 'harga_weekday' => 921609, 'harga_weekend' => 1100000, 'harga_highseason' => 1400000, 'gambar' => "images/akomodasi/industrial2/a.png"],
            ['judul' => "Glamping Reguler 1", 'jenis' => "Glamping", 'kasur' => "1 Tenda Arpenaz Quechua", 'merokok' => false, 'fasilitas' => ["Matras kasur tebal 10cm","1 lampu tenda","Colokan listrik 2 cabang"], 'makanan' => ["Teh, gula, dan kopi","2 mineral botol 1.5 liter"], 'max_orang' => 3, 'catatan' => ["Anak di bawah umur 5 tahun Free"], 'slot' => 8, 'harga_weekday' => 650000, 'harga_weekend' => 800000, 'harga_highseason' => 1050000, 'gambar' => "images/akomodasi/glamping_reguler/a.png"],
            ['judul' => "Glamping Reguler 2", 'jenis' => "Glamping", 'kasur' => "1 Tenda Arpenaz Quechua", 'merokok' => true, 'fasilitas' => ["Matras kasur tebal 10cm","1 lampu tenda","Colokan listrik 2 cabang"], 'makanan' => ["Teh, gula, dan kopi","2 mineral botol 1.5 liter"], 'max_orang' => 3, 'catatan' => ["Anak di bawah umur 5 tahun Free"], 'slot' => 7, 'harga_weekday' => 650000, 'harga_weekend' => 800000, 'harga_highseason' => 1050000, 'gambar' => "images/akomodasi/glamping_reguler/b.png"],
            ['judul' => "Glamping VIP 2", 'jenis' => "Glamping", 'kasur' => "1 Tenda Arpenaz Quechua", 'merokok' => true, 'fasilitas' => ["Matras kasur tebal 15cm","1 lampu tenda","VIP Eksklusif","Colokan listrik 3 cabang"], 'makanan' => ["Teh, gula, dan kopi","2 mineral botol 1.5 liter"], 'max_orang' => 4, 'catatan' => ["Anak di bawah umur 5 tahun Free"], 'slot' => 5, 'harga_weekday' => 921609, 'harga_weekend' => 1100000, 'harga_highseason' => 1400000, 'gambar' => "images/akomodasi/glamping_vip/b.png"],
            ['judul' => "Cabin Keluarga Deluxe", 'jenis' => "Cabin", 'kasur' => "King Bed (180×200) + Single Bed", 'merokok' => false, 'fasilitas' => ["TV kabel","Meja","AC","Lemari es","Ruang tamu","Balkon","Dapur"], 'makanan' => ["Fasilitas Membuat Kopi/Teh","Air Minum Gratis","Sarapan 6 pax"], 'max_orang' => 5, 'catatan' => ["Anak di bawah umur 5 tahun Free"], 'slot' => 2, 'harga_weekday' => 1500000, 'harga_weekend' => 1750000, 'harga_highseason' => 2200000, 'gambar' => "images/akomodasi/cabin1/b.png"],
            ['judul' => "Rumah Industrial Premium", 'jenis' => "Rumah Industrial", 'kasur' => "Queen Bed (140×200)", 'merokok' => false, 'fasilitas' => ["TV kabel","Meja","AC","Lemari es","Ruang tamu","Balkon","Dapur","Kipas angin"], 'makanan' => ["Fasilitas Membuat Kopi/Teh","Air Minum Gratis","Sarapan 6 pax"], 'max_orang' => 4, 'catatan' => ["Anak di bawah umur 5 tahun Free"], 'slot' => 3, 'harga_weekday' => 1100000, 'harga_weekend' => 1300000, 'harga_highseason' => 1650000, 'gambar' => "images/akomodasi/industrial2/b.png"],
            ['judul' => "Glamping Family", 'jenis' => "Glamping", 'kasur' => "2 Tenda Arpenaz Quechua", 'merokok' => true, 'fasilitas' => ["Matras kasur tebal 15cm","2 lampu tenda","Colokan listrik 3 cabang"], 'makanan' => ["Teh, gula, dan kopi","4 mineral botol 1.5 liter"], 'max_orang' => 6, 'catatan' => ["Anak di bawah umur 5 tahun Free"], 'slot' => 4, 'harga_weekday' => 1400000, 'harga_weekend' => 1650000, 'harga_highseason' => 2000000, 'gambar' => "images/akomodasi/glamping_vip/c.png"],
            ['judul' => "Cabin Riverside", 'jenis' => "Cabin", 'kasur' => "Queen Bed (140×200)", 'merokok' => true, 'fasilitas' => ["TV kabel","Meja","Kipas angin","Balkon","Dapur","View sungai"], 'makanan' => ["Fasilitas Membuat Kopi/Teh","Air Minum Gratis","Sarapan 4 pax"], 'max_orang' => 3, 'catatan' => ["Anak di bawah umur 5 tahun Free"], 'slot' => 4, 'harga_weekday' => 1050000, 'harga_weekend' => 1250000, 'harga_highseason' => 1600000, 'gambar' => "images/akomodasi/cabin3/b.png"],
            ['judul' => "Rumah Industrial Cozy", 'jenis' => "Rumah Industrial", 'kasur' => "Queen Bed (140×200)", 'merokok' => false, 'fasilitas' => ["TV kabel","Meja","Lemari es","Kipas angin","Dapur"], 'makanan' => ["Fasilitas Membuat Kopi/Teh","Air Minum Gratis","Sarapan 4 pax"], 'max_orang' => 3, 'catatan' => ["Anak di bawah umur 5 tahun Free"], 'slot' => 5, 'harga_weekday' => 850000, 'harga_weekend' => 1000000, 'harga_highseason' => 1280000, 'gambar' => "images/akomodasi/industrial1/b.png"],
            ['judul' => "Glamping Sunset View", 'jenis' => "Glamping", 'kasur' => "1 Tenda Arpenaz Quechua", 'merokok' => false, 'fasilitas' => ["Matras kasur tebal 15cm","1 lampu tenda","Colokan listrik 3 cabang"], 'makanan' => ["Teh, gula, dan kopi","2 mineral botol 1.5 liter"], 'max_orang' => 4, 'catatan' => ["Anak di bawah umur 5 tahun Free"], 'slot' => 6, 'harga_weekday' => 780000, 'harga_weekend' => 950000, 'harga_highseason' => 1200000, 'gambar' => "images/akomodasi/glamping_reguler/c.png"],
        ];

        foreach ($data as $item) {
            Accommodation::create($item);
        }
    }
}
